-- Ex 11

-- CERINTA: 
-- Sa se implementeze urmatoarele reguli pentru organizarea angajatilor :
-- 1. Suspendarea unui angajat
--      Cand statusul angajatului este actualizat la "Suspendat", compania
--      ii va reduce salariul cu 5%. Cu toate acestea, reducerea nu poate sa duca
--      salariul angajatului sub nivelul minim prevazut pentru jobul sau. 
--      Daca se ajunge la aceasta situatie,
--      salariul angajatului va lua valoarea minima mentionata anterior.
-- 2. Adaugarea unui nou angajat
--      La momentul efectuarii unei noi angajari se va tine cont de faptul ca salariul trebuie
--      sa fie cel minim corespunzator jobului pentru care lucreaza. De asemenea, daca numarul maxim de 
--      angajati permis pentru un cinematograful este depasit, 
--      se va afisa un mesaj de eroare care sa informeze utilizatorul despre aceasta situatie.


alter table angajati
disable all triggers;



-- tabel cu ajutorul caruia vom urmari operatiile efectuate
CREATE TABLE info_angajati(
    id_info NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod VARCHAR2(3),
    operatie varchar2(30),
    detalii_coloana_modificata varchar2(200),
    data_info date );



CREATE OR REPLACE TRIGGER trigger_ex11
    FOR INSERT OR UPDATE OF status_angajat ON angajati 
    COMPOUND TRIGGER
        record_info info_angajati%rowtype;
    BEFORE EACH ROW IS  
        minim joburi.salariu_minim%type;
        maxim_angajati constant number := 10;
        nr_angajati_in_prezent number;
        BEGIN
            if UPDATING then
                if :NEW.status_angajat = 'Suspendat' then
                    select salariu_minim into minim
                    from joburi 
                    where cod_job = :OLD.cod_job;
        
                    :NEW.salariu_angajat := :OLD.salariu_angajat - 0.05*:OLD.salariu_angajat;
        
                    if :NEW.salariu_angajat < minim then
                        :NEW.salariu_angajat := minim;
                    end if;
                
                    record_info.cod := :OLD.cod_angajat;
                    record_info.operatie := 'Suspendare';
                    record_info.detalii_coloana_modificata := 'Salariul a fost redus de la '||
                    :OLD.salariu_angajat||' la ' || :NEW.salariu_angajat 
                        || ', dar nu sub salariul minim (' || minim || ').';
                    record_info.data_info := sysdate;
                end if;
            elsif INSERTING then
                select salariu_minim into minim
                from joburi 
                where cod_job = :NEW.cod_job;
        
                if :NEW.salariu_angajat != minim then
                    RAISE_APPLICATION_ERROR(-20001, 'Salariul trebuie sa fie cel minim corespunzator jobului (' 
                        || minim || ').');
                end if;
            
                select count(*) into nr_angajati_in_prezent
                from angajati
                where cod_cinematograf = :NEW.cod_cinematograf;

                if nr_angajati_in_prezent >= maxim_angajati THEN
                    RAISE_APPLICATION_ERROR(-20002, 'Cinematograful a atins limita maxima de angajati (' 
                        || maxim_angajati || ').');
                end if;

                record_info.cod := :NEW.cod_angajat;
                record_info.operatie := 'Adaugare';
                record_info.detalii_coloana_modificata := 'Angajat nou cu salariul minim corespunzator jobului (' || minim || ').';
                record_info.data_info := sysdate;
            end if;
    END BEFORE EACH ROW;
    
    AFTER EACH ROW IS
        BEGIN
            if record_info.cod is NOT NULL then
                insert into info_angajati(cod, operatie, detalii_coloana_modificata, data_info)
                    values (record_info.cod, record_info.operatie, record_info.detalii_coloana_modificata, record_info.data_info);
                
                dbms_output.put_line('Cod angajat: ' || record_info.cod);
                dbms_output.put_line('Operatie: ' || record_info.operatie);
                dbms_output.put_line('Detalii modificare: ' || record_info.detalii_coloana_modificata);
                dbms_output.put_line('Data operatiei: ' || to_char(record_info.data_info, 'DD-MON-YYYY HH24:MI'));
            end if;
            
            -- resetam valorile
            record_info.cod := null;
            record_info.operatie := null;
            record_info.detalii_coloana_modificata := null;
            record_info.data_info := null;
        END AFTER EACH ROW;    
END;
/



-- verificare inserari corecte cu salariu corect
INSERT INTO angajati VALUES ('A28', 'J12', 'D7', 'C10','Florea', 'Alexandra', 2200, TO_DATE('20-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A29', 'J12', 'D7', 'C10','Onila', 'Matei', 2200, TO_DATE('21-DEC-24', 'DD-MON-YY'),'Activ');

-- verificare exceptii salariu
INSERT INTO angajati VALUES ('A30', 'J12', 'D7', 'C10','Pacurariu', 'Alexandra', 2201, TO_DATE('21-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A31', 'J12', 'D7', 'C10','Pacurariu', 'Razvan', 2199, TO_DATE('21-DEC-24', 'DD-MON-YY'),'Activ');


-- verificare pt nr maxim de angajati
INSERT INTO angajati VALUES ('A32', 'J12', 'D7', 'C10','Nume1', 'Prenume1', 2200, TO_DATE('20-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A33', 'J12', 'D7', 'C10','Nume2', 'Prenume2', 2200, TO_DATE('21-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A34', 'J12', 'D7', 'C10','Nume3', 'Prenume3', 2200, TO_DATE('22-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A35', 'J12', 'D7', 'C10','Nume4', 'Prenume4', 2200, TO_DATE('23-DEC-24', 'DD-MON-YY'),'Activ');
INSERT INTO angajati VALUES ('A36', 'J12', 'D7', 'C10','Nume5', 'Prenume5', 2200, TO_DATE('24-DEC-24', 'DD-MON-YY'),'Activ');
-- la acest insert trebuie sa apara eroare de depasire a nr maxim de angajati
-- deoarece am inserat al 11-lea angajat al cinematografului C10
INSERT INTO angajati VALUES ('A37', 'J12', 'D7', 'C10','Nume6', 'Prenume6', 2200, TO_DATE('25-DEC-24', 'DD-MON-YY'),'Activ');


select count(*), cod_cinematograf
from angajati
group by cod_cinematograf;


select * from angajati;

--verificare update
update angajati
set status_angajat = 'Suspendat'
where cod_angajat = 'A1';

--verificare update, dar reducerea de salariu este mai mica decat salariul minim
update angajati
set status_angajat = 'Suspendat'
where cod_angajat = 'A4';



----------------------------- resetare angajat 'A1' -------------------------
update angajati
set status_angajat = 'Activ'
where cod_angajat = 'A1';

update angajati
set salariu_angajat = 4500
where cod_angajat = 'A1';
----------------------------------------------------------------------------------

------------------------------- resetare angajat 'A4' --------------------------------
update angajati
set status_angajat = 'Activ'
where cod_angajat = 'A4';

update angajati
set salariu_angajat = 4050
where cod_angajat = 'A4';
-------------------------------------------------------------------------------------

--------------------------- resetare numar de angajati --------------------------
delete from angajati
where cod_angajat = 'A29';

delete from angajati
where cod_angajat = 'A28';

delete from angajati
where cod_angajat = 'A32';

delete from angajati
where cod_angajat = 'A33';

delete from angajati
where cod_angajat = 'A34';

delete from angajati
where cod_angajat = 'A35';

delete from angajati
where cod_angajat = 'A36';

delete from angajati
where cod_angajat = 'A37';
----------------------------------------------------------------------------------